// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NTVLoggerLevel)
{
    NTVLoggerLevelVerbose = 0,
    NTVLoggerLevelDebug = 1,
    NTVLoggerLevelInfo = 2,
    NTVLoggerLevelWarning = 3,
    NTVLoggerLevelError = 4,
};
