// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export enum LoggerLevel {
    VERBOSE = 0,
    DEBUG = 1,
    INFO = 2,
    WARNING = 3,
    ERROR = 4,
}

export interface LoggerPlatformService {
    v(message: string): void;
    d(message: string): void;
    i(message: string): void;
    w(message: string): void;
    e(message: string): void;
    setGroup(group: string): void;
}

export interface Logger {
    setPlatformService(ps: LoggerPlatformService): void;
    getPlatformService(): LoggerPlatformService;
    hasPlatformService(): boolean;
    allowedLevel(level: LoggerLevel): boolean;
    setLevel(level: LoggerLevel): void;
}
export interface Logger_statics {
    shared(): Logger;
    v(message: string): void;
    d(message: string): void;
    i(message: string): void;
    w(message: string): void;
    e(message: string): void;
    setGroup(group: string): void;
}

export interface Logger_statics {
    Logger: Logger_statics;
}
