// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/io/NTVFileHelper.hpp"  // my header
#include "nativium/io/NTVFileHelperPlatformService.hpp"

namespace djinni_generated {

em::val NTVFileHelper::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "setPlatformService",
        "getPlatformService",
        "hasPlatformService",
    });
    return methods;
}

em::val NTVFileHelper::shared() {
    auto r = ::nativium::io::FileHelper::shared();
    return ::djinni_generated::NTVFileHelper::fromCpp(r);
}
void NTVFileHelper::setPlatformService(const CppType& self, const em::val& w_ps) {
    self->setPlatformService(::djinni_generated::NTVFileHelperPlatformService::toCpp(w_ps));
}
em::val NTVFileHelper::getPlatformService(const CppType& self) {
    auto r = self->getPlatformService();
    return ::djinni_generated::NTVFileHelperPlatformService::fromCpp(r);
}
bool NTVFileHelper::hasPlatformService(const CppType& self) {
    auto r = self->hasPlatformService();
    return ::djinni::Bool::fromCpp(r);
}
bool NTVFileHelper::createFile(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::createFile(::djinni::String::toCpp(w_path));
    return ::djinni::Bool::fromCpp(r);
}
bool NTVFileHelper::createFileWithStringContent(const std::string& w_path,const std::string& w_content) {
    auto r = ::nativium::io::FileHelper::createFileWithStringContent(::djinni::String::toCpp(w_path),
                                ::djinni::String::toCpp(w_content));
    return ::djinni::Bool::fromCpp(r);
}
bool NTVFileHelper::createFileWithBinaryContent(const std::string& w_path,const em::val& w_content) {
    auto r = ::nativium::io::FileHelper::createFileWithBinaryContent(::djinni::String::toCpp(w_path),
                                ::djinni::Binary::toCpp(w_content));
    return ::djinni::Bool::fromCpp(r);
}
bool NTVFileHelper::createDir(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::createDir(::djinni::String::toCpp(w_path));
    return ::djinni::Bool::fromCpp(r);
}
em::val NTVFileHelper::listFiles(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::listFiles(::djinni::String::toCpp(w_path));
    return ::djinni::List<::djinni::String>::fromCpp(r);
}
std::string NTVFileHelper::getExtension(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::getExtension(::djinni::String::toCpp(w_path));
    return ::djinni::String::fromCpp(r);
}
std::string NTVFileHelper::getFilename(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::getFilename(::djinni::String::toCpp(w_path));
    return ::djinni::String::fromCpp(r);
}
std::string NTVFileHelper::getBasename(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::getBasename(::djinni::String::toCpp(w_path));
    return ::djinni::String::fromCpp(r);
}
std::string NTVFileHelper::getFilenameFromUrl(const std::string& w_url) {
    auto r = ::nativium::io::FileHelper::getFilenameFromUrl(::djinni::String::toCpp(w_url));
    return ::djinni::String::fromCpp(r);
}
std::string NTVFileHelper::getBasenameFromUrl(const std::string& w_url) {
    auto r = ::nativium::io::FileHelper::getBasenameFromUrl(::djinni::String::toCpp(w_url));
    return ::djinni::String::fromCpp(r);
}
bool NTVFileHelper::removeFile(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::removeFile(::djinni::String::toCpp(w_path));
    return ::djinni::Bool::fromCpp(r);
}
bool NTVFileHelper::removeDir(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::removeDir(::djinni::String::toCpp(w_path));
    return ::djinni::Bool::fromCpp(r);
}
bool NTVFileHelper::isDir(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::isDir(::djinni::String::toCpp(w_path));
    return ::djinni::Bool::fromCpp(r);
}
bool NTVFileHelper::isFile(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::isFile(::djinni::String::toCpp(w_path));
    return ::djinni::Bool::fromCpp(r);
}
int64_t NTVFileHelper::getFileSize(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::getFileSize(::djinni::String::toCpp(w_path));
    return ::djinni::I64::fromCpp(r);
}
bool NTVFileHelper::copyFile(const std::string& w_from,const std::string& w_to) {
    auto r = ::nativium::io::FileHelper::copyFile(::djinni::String::toCpp(w_from),
             ::djinni::String::toCpp(w_to));
    return ::djinni::Bool::fromCpp(r);
}
bool NTVFileHelper::moveFile(const std::string& w_from,const std::string& w_to) {
    auto r = ::nativium::io::FileHelper::moveFile(::djinni::String::toCpp(w_from),
             ::djinni::String::toCpp(w_to));
    return ::djinni::Bool::fromCpp(r);
}
std::string NTVFileHelper::join(const std::string& w_first,const std::string& w_second) {
    auto r = ::nativium::io::FileHelper::join(::djinni::String::toCpp(w_first),
         ::djinni::String::toCpp(w_second));
    return ::djinni::String::fromCpp(r);
}
std::string NTVFileHelper::getFileContentAsString(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::getFileContentAsString(::djinni::String::toCpp(w_path));
    return ::djinni::String::fromCpp(r);
}
em::val NTVFileHelper::getFileContentAsBinary(const std::string& w_path) {
    auto r = ::nativium::io::FileHelper::getFileContentAsBinary(::djinni::String::toCpp(w_path));
    return ::djinni::Binary::fromCpp(r);
}
std::string NTVFileHelper::getHomeDir() {
    auto r = ::nativium::io::FileHelper::getHomeDir();
    return ::djinni::String::fromCpp(r);
}

EMSCRIPTEN_BINDINGS(nativium_io_file_helper) {
    em::class_<::nativium::io::FileHelper>("FileHelper")
        .smart_ptr<std::shared_ptr<::nativium::io::FileHelper>>("FileHelper")
        .function("nativeDestroy", &NTVFileHelper::nativeDestroy)
        .class_function("shared", NTVFileHelper::shared)
        .function("setPlatformService", NTVFileHelper::setPlatformService)
        .function("getPlatformService", NTVFileHelper::getPlatformService)
        .function("hasPlatformService", NTVFileHelper::hasPlatformService)
        .class_function("createFile", NTVFileHelper::createFile)
        .class_function("createFileWithStringContent", NTVFileHelper::createFileWithStringContent)
        .class_function("createFileWithBinaryContent", NTVFileHelper::createFileWithBinaryContent)
        .class_function("createDir", NTVFileHelper::createDir)
        .class_function("listFiles", NTVFileHelper::listFiles)
        .class_function("getExtension", NTVFileHelper::getExtension)
        .class_function("getFilename", NTVFileHelper::getFilename)
        .class_function("getBasename", NTVFileHelper::getBasename)
        .class_function("getFilenameFromUrl", NTVFileHelper::getFilenameFromUrl)
        .class_function("getBasenameFromUrl", NTVFileHelper::getBasenameFromUrl)
        .class_function("removeFile", NTVFileHelper::removeFile)
        .class_function("removeDir", NTVFileHelper::removeDir)
        .class_function("isDir", NTVFileHelper::isDir)
        .class_function("isFile", NTVFileHelper::isFile)
        .class_function("getFileSize", NTVFileHelper::getFileSize)
        .class_function("copyFile", NTVFileHelper::copyFile)
        .class_function("moveFile", NTVFileHelper::moveFile)
        .class_function("join", NTVFileHelper::join)
        .class_function("getFileContentAsString", NTVFileHelper::getFileContentAsString)
        .class_function("getFileContentAsBinary", NTVFileHelper::getFileContentAsBinary)
        .class_function("getHomeDir", NTVFileHelper::getHomeDir)
        ;
}

}  // namespace djinni_generated
