// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/io/FileHelperPlatformService.hpp"

namespace djinni_generated {

struct NTVFileHelperPlatformService : ::djinni::JsInterface<::nativium::io::FileHelperPlatformService, NTVFileHelperPlatformService> {
    using CppType = std::shared_ptr<::nativium::io::FileHelperPlatformService>;
    using CppOptType = std::shared_ptr<::nativium::io::FileHelperPlatformService>;
    using JsType = em::val;
    using Boxed = NTVFileHelperPlatformService;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) { return fromCppOpt(c); }


};

}  // namespace djinni_generated
