// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NTVEnumeratorCustomerStatusEnum)
{
    NTVEnumeratorCustomerStatusEnumActive = 0,
    NTVEnumeratorCustomerStatusEnumInactive = 1,
};
