// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/systemservice/NTVSystemServiceCustomerSystemService.hpp"  // my header
#include "com/nativium/systemservice/NTVSystemServiceCustomerSystemServiceLoginData.hpp"
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVSystemServiceCustomerSystemService::NTVSystemServiceCustomerSystemService() : ::djinni::JniInterface<::nativium::systemservice::CustomerSystemService, NTVSystemServiceCustomerSystemService>("com/nativium/systemservice/CustomerSystemService$CppProxy") {}

NTVSystemServiceCustomerSystemService::~NTVSystemServiceCustomerSystemService() = default;


CJNIEXPORT void JNICALL Java_com_nativium_systemservice_CustomerSystemService_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::nativium::systemservice::CustomerSystemService>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nativium_systemservice_CustomerSystemService_login(JNIEnv* jniEnv, jobject /*this*/, jstring j_username, jstring j_password)
{
    try {
        auto r = ::nativium::systemservice::CustomerSystemService::login(::djinni::String::toCpp(jniEnv, j_username),
                                                                         ::djinni::String::toCpp(jniEnv, j_password));
        return ::djinni::release(::djinni_generated::NTVSystemServiceCustomerSystemServiceLoginData::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
