// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainTodo.h"
#import <Foundation/Foundation.h>


@interface NTVRepositoryTodoRepository : NSObject

+ (void)truncate;

+ (nonnull NTVDomainTodo *)findById:(int64_t)id;

+ (nonnull NSArray<NTVDomainTodo *> *)findAllOrderByCreatedAtDesc;

+ (nonnull NSArray<NTVDomainTodo *> *)findByTitle:(nonnull NSString *)title;

+ (BOOL)removeById:(int64_t)id;

+ (int64_t)update:(int64_t)id
             todo:(nonnull NTVDomainTodo *)todo;

+ (int64_t)insert:(nonnull NTVDomainTodo *)todo;

+ (int64_t)add:(nonnull NTVDomainTodo *)todo;

+ (BOOL)setDoneById:(int64_t)id
               done:(BOOL)done;

+ (int64_t)count;

@end
