// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.util;

public enum LoggerLevel {
    VERBOSE,
    DEBUG,
    INFO,
    WARNING,
    ERROR,
    ;
}
