// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/systemservice/NTVSystemServiceCustomerSystemServiceLoginData.h"


@implementation NTVSystemServiceCustomerSystemServiceLoginData

- (nonnull instancetype)initWithResponse:(nonnull NTVDomainResponse *)response
                                customer:(nonnull NTVDomainCustomer *)customer
{
    if (self = [super init]) {
        _response = response;
        _customer = customer;
    }
    return self;
}

+ (nonnull instancetype)customerSystemServiceLoginDataWithResponse:(nonnull NTVDomainResponse *)response
                                                          customer:(nonnull NTVDomainCustomer *)customer
{
    return [[self alloc] initWithResponse:response
                                 customer:customer];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p response:%@ customer:%@>", self.class, (void *)self, self.response, self.customer];
}

#endif
@end
