// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/systemservice/NTVSystemServiceCustomerSystemServiceLoginData.h"
#include "nativium/systemservice/CustomerSystemServiceLoginData.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVSystemServiceCustomerSystemServiceLoginData;

namespace djinni_generated {

struct CustomerSystemServiceLoginData
{
    using CppType = ::nativium::systemservice::CustomerSystemServiceLoginData;
    using ObjcType = NTVSystemServiceCustomerSystemServiceLoginData*;

    using Boxed = CustomerSystemServiceLoginData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
