// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/systemservice/NTVSystemServiceCustomerSystemServiceLoginData.h"
#import <Foundation/Foundation.h>


@interface NTVSystemServiceCustomerSystemService : NSObject

+ (nonnull NTVSystemServiceCustomerSystemServiceLoginData *)login:(nonnull NSString *)username
                                                         password:(nonnull NSString *)password;

@end
