// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.text;

import com.snapchat.djinni.NativeObjectManager;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class StringHelper {
    public static native String trim(String value);

    public static native String leftTrim(String value);

    public static native String rightTrim(String value);

    public static native String toLower(String value);

    public static native String toUpper(String value);

    public static native ArrayList<String> split(String text, String sep, boolean trimEmpty);

    public static native String encodeUri(String value);

    public static native String decodeUri(String value);

    public static final class CppProxy extends StringHelper
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);
    }
}
