// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <string>
#include <vector>

namespace nativium { namespace text {

class StringHelper {
public:
    virtual ~StringHelper() = default;

    static std::string trim(const std::string & value);

    static std::string leftTrim(const std::string & value);

    static std::string rightTrim(const std::string & value);

    static std::string toLower(const std::string & value);

    static std::string toUpper(const std::string & value);

    static std::vector<std::string> split(const std::string & text, const std::string & sep, bool trimEmpty);

    static std::string encodeUri(const std::string & value);

    static std::string decodeUri(const std::string & value);
};

} }  // namespace nativium::text
