// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.helper;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class SharedDataHelper {
    public static native void setCustomer(com.nativium.domain.Customer value);

    public static native com.nativium.domain.Customer getCustomer();

    public static native void storeCustomer();

    public static native void setDemoFlag(boolean value);

    public static native boolean getDemoFlag();

    public static final class CppProxy extends SharedDataHelper
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);
    }
}
