// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/helper/NTVStringHelper.hpp"  // my header

namespace djinni_generated {

em::val NTVStringHelper::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

std::string NTVStringHelper::trim(const std::string& w_value) {
    auto r = ::nativium::helper::StringHelper::trim(::djinni::String::toCpp(w_value));
    return ::djinni::String::fromCpp(r);
}
std::string NTVStringHelper::leftTrim(const std::string& w_value) {
    auto r = ::nativium::helper::StringHelper::leftTrim(::djinni::String::toCpp(w_value));
    return ::djinni::String::fromCpp(r);
}
std::string NTVStringHelper::rightTrim(const std::string& w_value) {
    auto r = ::nativium::helper::StringHelper::rightTrim(::djinni::String::toCpp(w_value));
    return ::djinni::String::fromCpp(r);
}
std::string NTVStringHelper::toLower(const std::string& w_value) {
    auto r = ::nativium::helper::StringHelper::toLower(::djinni::String::toCpp(w_value));
    return ::djinni::String::fromCpp(r);
}
std::string NTVStringHelper::toUpper(const std::string& w_value) {
    auto r = ::nativium::helper::StringHelper::toUpper(::djinni::String::toCpp(w_value));
    return ::djinni::String::fromCpp(r);
}
em::val NTVStringHelper::split(const std::string& w_text,const std::string& w_sep,bool w_trimEmpty) {
    auto r = ::nativium::helper::StringHelper::split(::djinni::String::toCpp(w_text),
          ::djinni::String::toCpp(w_sep),
          ::djinni::Bool::toCpp(w_trimEmpty));
    return ::djinni::List<::djinni::String>::fromCpp(r);
}

EMSCRIPTEN_BINDINGS(nativium_helper_string_helper) {
    em::class_<::nativium::helper::StringHelper>("StringHelper")
        .smart_ptr<std::shared_ptr<::nativium::helper::StringHelper>>("StringHelper")
        .function("nativeDestroy", &NTVStringHelper::nativeDestroy)
        .class_function("trim", NTVStringHelper::trim)
        .class_function("leftTrim", NTVStringHelper::leftTrim)
        .class_function("rightTrim", NTVStringHelper::rightTrim)
        .class_function("toLower", NTVStringHelper::toLower)
        .class_function("toUpper", NTVStringHelper::toUpper)
        .class_function("split", NTVStringHelper::split)
        ;
}

}  // namespace djinni_generated
