// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/net/http/HttpRequestParam.hpp"

namespace djinni_generated {

struct NTVHttpRequestParam
{
    using CppType = ::nativium::net::http::HttpRequestParam;
    using JsType = em::val;
    using Boxed = NTVHttpRequestParam;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
