// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/net/http/NTVHttpRequest.hpp"  // my header
#include "nativium/net/http/NTVHttpCookie.hpp"
#include "nativium/net/http/NTVHttpHeader.hpp"
#include "nativium/net/http/NTVHttpMethod.hpp"
#include "nativium/net/http/NTVHttpRequestParam.hpp"

namespace djinni_generated {

auto NTVHttpRequest::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["url"]),
            ::djinni_generated::NTVHttpMethod::Boxed::toCpp(j["method"]),
            ::djinni::List<::djinni_generated::NTVHttpRequestParam>::Boxed::toCpp(j["params"]),
            ::djinni::List<::djinni_generated::NTVHttpHeader>::Boxed::toCpp(j["headers"]),
            ::djinni::List<::djinni_generated::NTVHttpCookie>::Boxed::toCpp(j["cookies"]),
            ::djinni::String::Boxed::toCpp(j["body"])};
}
auto NTVHttpRequest::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("url", ::djinni::String::Boxed::fromCpp(c.url));
    js.set("method", ::djinni_generated::NTVHttpMethod::Boxed::fromCpp(c.method));
    js.set("params", ::djinni::List<::djinni_generated::NTVHttpRequestParam>::Boxed::fromCpp(c.params));
    js.set("headers", ::djinni::List<::djinni_generated::NTVHttpHeader>::Boxed::fromCpp(c.headers));
    js.set("cookies", ::djinni::List<::djinni_generated::NTVHttpCookie>::Boxed::fromCpp(c.cookies));
    js.set("body", ::djinni::String::Boxed::fromCpp(c.body));
    return js;
}

}  // namespace djinni_generated
