// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/net/http/NTVHttpClientPlatformService.hpp"  // my header
#include "nativium/net/http/NTVHttpRequest.hpp"
#include "nativium/net/http/NTVHttpResponse.hpp"

namespace djinni_generated {

em::val NTVHttpClientPlatformService::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "doRequest",
    });
    return methods;
}

em::val NTVHttpClientPlatformService::doRequest(const CppType& self, const em::val& w_request) {
    try {
        auto r = self->doRequest(::djinni_generated::NTVHttpRequest::toCpp(w_request));
        return ::djinni_generated::NTVHttpResponse::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni_generated::NTVHttpResponse>::handleNativeException(e);
    }
}

::nativium::net::http::HttpResponse NTVHttpClientPlatformService::JsProxy::doRequest(const ::nativium::net::http::HttpRequest & request) {
    auto ret = callMethod("doRequest", ::djinni_generated::NTVHttpRequest::fromCpp(request));
    checkError(ret);
    return ::djinni_generated::NTVHttpResponse::toCpp(ret);
}

EMSCRIPTEN_BINDINGS(nativium_net_http_http_client_platform_service) {
    em::class_<::nativium::net::http::HttpClientPlatformService>("HttpClientPlatformService")
        .smart_ptr<std::shared_ptr<::nativium::net::http::HttpClientPlatformService>>("HttpClientPlatformService")
        .function("nativeDestroy", &NTVHttpClientPlatformService::nativeDestroy)
        .function("doRequest", NTVHttpClientPlatformService::doRequest)
        ;
}

}  // namespace djinni_generated
