// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/net/http/HttpClient.hpp"

namespace djinni_generated {

struct NTVHttpClient : ::djinni::JsInterface<::nativium::net::http::HttpClient, NTVHttpClient> {
    using CppType = std::shared_ptr<::nativium::net::http::HttpClient>;
    using CppOptType = std::shared_ptr<::nativium::net::http::HttpClient>;
    using JsType = em::val;
    using Boxed = NTVHttpClient;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        djinni::checkForNull(c.get(), "NTVHttpClient::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val shared();
    static void setPlatformService(const CppType& self, const em::val& w_ps);
    static em::val getPlatformService(const CppType& self);
    static bool hasPlatformService(const CppType& self);
    static em::val doRequest(const CppType& self, const em::val& w_request);
    static void setLogger(const CppType& self, const em::val& w_logger);
    static em::val getLogger(const CppType& self);
    static bool hasLogger(const CppType& self);

};

}  // namespace djinni_generated
