// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/net/http/HttpMethod.hpp"

namespace djinni_generated {

struct NTVHttpMethod: ::djinni::WasmEnum<::nativium::net::http::HttpMethod> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
