// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "nativium/domain/Customer.hpp"
#include <string>

namespace nativium { namespace helper {

class CustomerHelper {
public:
    virtual ~CustomerHelper() = default;

    static bool isLogged();

    static std::string getToken();

    static ::nativium::domain::Customer create();

    static void onCustomerLogin(const ::nativium::domain::Customer & customer);
};

} }  // namespace nativium::helper
