// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <string>

namespace nativium { namespace helper {

class EnvironmentHelper {
public:
    virtual ~EnvironmentHelper() = default;

    static std::string getSecretKey();
};

} }  // namespace nativium::helper
