// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <string>

namespace nativium { namespace helper {

class SecurityHelper {
public:
    virtual ~SecurityHelper() = default;

    static std::string generateUuidV4();
};

} }  // namespace nativium::helper
