// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "nativium/domain/Customer.hpp"

namespace nativium { namespace helper {

class SharedDataHelper {
public:
    virtual ~SharedDataHelper() = default;

    static void setCustomer(const ::nativium::domain::Customer & value);

    static ::nativium::domain::Customer getCustomer();

    static void storeCustomer();

    static void setDemoFlag(bool value);

    static bool getDemoFlag();
};

} }  // namespace nativium::helper
