// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "nativium/domain/Todo.hpp"

namespace nativium { namespace helper {

class TodoHelper {
public:
    virtual ~TodoHelper() = default;

    static ::nativium::domain::Todo create();
};

} }  // namespace nativium::helper
