// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/data/NTVSharedDataPlatformService.hpp"  // my header

namespace djinni_generated {


EMSCRIPTEN_BINDINGS(nativium_data_shared_data_platform_service) {
    em::class_<::nativium::data::SharedDataPlatformService>("SharedDataPlatformService")
        .smart_ptr<std::shared_ptr<::nativium::data::SharedDataPlatformService>>("SharedDataPlatformService")
        .function("nativeDestroy", &NTVSharedDataPlatformService::nativeDestroy)
        ;
}

}  // namespace djinni_generated
