// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/data/SharedDataPlatformService.hpp"

namespace djinni_generated {

struct NTVSharedDataPlatformService : ::djinni::JsInterface<::nativium::data::SharedDataPlatformService, NTVSharedDataPlatformService> {
    using CppType = std::shared_ptr<::nativium::data::SharedDataPlatformService>;
    using CppOptType = std::shared_ptr<::nativium::data::SharedDataPlatformService>;
    using JsType = em::val;
    using Boxed = NTVSharedDataPlatformService;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        djinni::checkForNull(c.get(), "NTVSharedDataPlatformService::fromCpp");
        return fromCppOpt(c);
    }


};

}  // namespace djinni_generated
