// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/time/NTVDateTime.hpp"  // my header

namespace djinni_generated {

em::val NTVDateTime::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

em::val NTVDateTime::getDateTimeFromString(const std::string& w_value) {
    try {
        auto r = ::nativium::time::DateTime::getDateTimeFromString(::djinni::String::toCpp(w_value));
        return ::djinni::Date::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
std::string NTVDateTime::getStringFromDateTime(const em::val& w_value) {
    try {
        auto r = ::nativium::time::DateTime::getStringFromDateTime(::djinni::Date::toCpp(w_value));
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
std::string NTVDateTime::getCurrentDateTimeAsString() {
    try {
        auto r = ::nativium::time::DateTime::getCurrentDateTimeAsString();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
em::val NTVDateTime::getCurrentDateTime() {
    try {
        auto r = ::nativium::time::DateTime::getCurrentDateTime();
        return ::djinni::Date::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
em::val NTVDateTime::getDateTimeFromSeconds(int64_t w_value) {
    try {
        auto r = ::nativium::time::DateTime::getDateTimeFromSeconds(::djinni::I64::toCpp(w_value));
        return ::djinni::Date::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
em::val NTVDateTime::getDateTimeFromMilliseconds(int64_t w_value) {
    try {
        auto r = ::nativium::time::DateTime::getDateTimeFromMilliseconds(::djinni::I64::toCpp(w_value));
        return ::djinni::Date::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
int64_t NTVDateTime::getTimestampInMillisecondsFromDateTime(const em::val& w_value) {
    try {
        auto r = ::nativium::time::DateTime::getTimestampInMillisecondsFromDateTime(::djinni::Date::toCpp(w_value));
        return ::djinni::I64::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
int64_t NTVDateTime::getTimestampInSecondsFromDateTime(const em::val& w_value) {
    try {
        auto r = ::nativium::time::DateTime::getTimestampInSecondsFromDateTime(::djinni::Date::toCpp(w_value));
        return ::djinni::I64::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
std::string NTVDateTime::getCurrentTimestampInSecondsAsString() {
    try {
        auto r = ::nativium::time::DateTime::getCurrentTimestampInSecondsAsString();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
int64_t NTVDateTime::getCurrentTimestampInSeconds() {
    try {
        auto r = ::nativium::time::DateTime::getCurrentTimestampInSeconds();
        return ::djinni::I64::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
std::string NTVDateTime::getCurrentTimestampInMillisecondsAsString() {
    try {
        auto r = ::nativium::time::DateTime::getCurrentTimestampInMillisecondsAsString();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
int64_t NTVDateTime::getCurrentTimestampInMilliseconds() {
    try {
        auto r = ::nativium::time::DateTime::getCurrentTimestampInMilliseconds();
        return ::djinni::I64::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}

EMSCRIPTEN_BINDINGS(nativium_time_date_time) {
    em::class_<::nativium::time::DateTime>("DateTime")
        .smart_ptr<std::shared_ptr<::nativium::time::DateTime>>("DateTime")
        .function("nativeDestroy", &NTVDateTime::nativeDestroy)
        .class_function("getDateTimeFromString", NTVDateTime::getDateTimeFromString)
        .class_function("getStringFromDateTime", NTVDateTime::getStringFromDateTime)
        .class_function("getCurrentDateTimeAsString", NTVDateTime::getCurrentDateTimeAsString)
        .class_function("getCurrentDateTime", NTVDateTime::getCurrentDateTime)
        .class_function("getDateTimeFromSeconds", NTVDateTime::getDateTimeFromSeconds)
        .class_function("getDateTimeFromMilliseconds", NTVDateTime::getDateTimeFromMilliseconds)
        .class_function("getTimestampInMillisecondsFromDateTime", NTVDateTime::getTimestampInMillisecondsFromDateTime)
        .class_function("getTimestampInSecondsFromDateTime", NTVDateTime::getTimestampInSecondsFromDateTime)
        .class_function("getCurrentTimestampInSecondsAsString", NTVDateTime::getCurrentTimestampInSecondsAsString)
        .class_function("getCurrentTimestampInSeconds", NTVDateTime::getCurrentTimestampInSeconds)
        .class_function("getCurrentTimestampInMillisecondsAsString", NTVDateTime::getCurrentTimestampInMillisecondsAsString)
        .class_function("getCurrentTimestampInMilliseconds", NTVDateTime::getCurrentTimestampInMilliseconds)
        ;
}

}  // namespace djinni_generated
