// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/util/LoggerPlatformService.hpp"

namespace djinni_generated {

struct NTVLoggerPlatformService : ::djinni::JsInterface<::nativium::util::LoggerPlatformService, NTVLoggerPlatformService> {
    using CppType = std::shared_ptr<::nativium::util::LoggerPlatformService>;
    using CppOptType = std::shared_ptr<::nativium::util::LoggerPlatformService>;
    using JsType = em::val;
    using Boxed = NTVLoggerPlatformService;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) { return fromCppOpt(c); }


};

}  // namespace djinni_generated
