// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/util/LoggerLevel.hpp"

namespace djinni_generated {

struct NTVLoggerLevel: ::djinni::WasmEnum<::nativium::util::LoggerLevel> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
