// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/util/NTVLoggerPlatformService.hpp"  // my header

namespace djinni_generated {


EMSCRIPTEN_BINDINGS(nativium_util_logger_platform_service) {
    em::class_<::nativium::util::LoggerPlatformService>("LoggerPlatformService")
        .smart_ptr<std::shared_ptr<::nativium::util::LoggerPlatformService>>("LoggerPlatformService")
        .function("nativeDestroy", &NTVLoggerPlatformService::nativeDestroy)
        ;
}

}  // namespace djinni_generated
