// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/util/NTVLoggerLevel.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init_nativium_util_logger_level_consts, (), {
        Module.LoggerLevel =  {
            VERBOSE : 0,
            DEBUG : 1,
            INFO : 2,
            WARNING : 3,
            ERROR : 4,
        }
    })
}

void NTVLoggerLevel::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init_nativium_util_logger_level_consts();
    });
}

EMSCRIPTEN_BINDINGS(nativium_util_logger_level) {
    NTVLoggerLevel::staticInitializeConstants();
}

}  // namespace djinni_generated
