// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <functional>

namespace nativium { namespace util {

enum class LoggerLevel : int {
    VERBOSE = 0,
    DEBUG = 1,
    INFO = 2,
    WARNING = 3,
    ERROR = 4,
};

constexpr const char* toString(LoggerLevel e) noexcept {
    constexpr const char* names[] = {
        "verbose",
        "debug",
        "info",
        "warning",
        "error",
    };
    return names[static_cast<int>(e)];
}

} }  // namespace nativium::util

namespace std {

template <>
struct hash<::nativium::util::LoggerLevel> {
    size_t operator()(::nativium::util::LoggerLevel type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
