// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/enumerator/CustomerStatusEnum.hpp"

namespace djinni_generated {

class NTVEnumeratorCustomerStatusEnum final : ::djinni::JniEnum {
public:
    using CppType = ::nativium::enumerator::CustomerStatusEnum;
    using JniType = jobject;

    using Boxed = NTVEnumeratorCustomerStatusEnum;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NTVEnumeratorCustomerStatusEnum>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NTVEnumeratorCustomerStatusEnum>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NTVEnumeratorCustomerStatusEnum() : JniEnum("com/nativium/enumerator/CustomerStatusEnum") {}
    friend ::djinni::JniClass<NTVEnumeratorCustomerStatusEnum>;
};

}  // namespace djinni_generated
