// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/data/SharedData.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVSharedData;

namespace djinni_generated {

class SharedData
{
public:
    using CppType = std::shared_ptr<::nativium::data::SharedData>;
    using CppOptType = std::shared_ptr<::nativium::data::SharedData>;
    using ObjcType = NTVSharedData*;

    using Boxed = SharedData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

