// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <functional>

namespace nativium { namespace enumerator {

enum class CustomerStatusEnum : int {
    ACTIVE = 0,
    INACTIVE = 1,
};

constexpr const char* toString(CustomerStatusEnum e) noexcept {
    constexpr const char* names[] = {
        "active",
        "inactive",
    };
    return names[static_cast<int>(e)];
}

} }  // namespace nativium::enumerator

namespace std {

template <>
struct hash<::nativium::enumerator::CustomerStatusEnum> {
    size_t operator()(::nativium::enumerator::CustomerStatusEnum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
