// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpServerConfig.h"
#import <Foundation/Foundation.h>
@class NTVHttpServer;


@interface NTVHttpServer : NSObject

+ (nullable NTVHttpServer *)shared;

- (void)initialize:(nonnull NTVHttpServerConfig *)config;

- (nonnull NTVHttpServerConfig *)getConfig;

- (void)start;

- (void)stop;

- (void)waitForTermination;

- (int32_t)getSocketPort;

- (nonnull NSString *)getSocketHost;

- (nonnull NSString *)getSocketAddress;

- (BOOL)isSocketSecure;

- (BOOL)isRunning;

@end
