// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpServerConfig+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto HttpServerConfig::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.port),
            ::djinni::String::toCpp(obj.staticPath)};
}

auto HttpServerConfig::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NTVHttpServerConfig alloc] initWithPort:(::djinni::I32::fromCpp(cpp.port))
                                          staticPath:(::djinni::String::fromCpp(cpp.staticPath))];
}

}  // namespace djinni_generated
