// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/systemservice/CustomerSystemService.hpp"

namespace djinni_generated {

struct NTVSystemServiceCustomerSystemService : ::djinni::JsInterface<::nativium::systemservice::CustomerSystemService, NTVSystemServiceCustomerSystemService> {
    using CppType = std::shared_ptr<::nativium::systemservice::CustomerSystemService>;
    using CppOptType = std::shared_ptr<::nativium::systemservice::CustomerSystemService>;
    using JsType = em::val;
    using Boxed = NTVSystemServiceCustomerSystemService;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        djinni::checkForNull(c.get(), "NTVSystemServiceCustomerSystemService::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val login(const std::string& w_username,const std::string& w_password);

};

}  // namespace djinni_generated
