// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainResponseError.h"


@implementation NTVDomainResponseError

- (nonnull instancetype)initWithField:(nonnull NSString *)field
                              message:(nonnull NSString *)message
{
    if (self = [super init]) {
        _field = [field copy];
        _message = [message copy];
    }
    return self;
}

+ (nonnull instancetype)responseErrorWithField:(nonnull NSString *)field
                                       message:(nonnull NSString *)message
{
    return [[self alloc] initWithField:field
                               message:message];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p field:%@ message:%@>", self.class, (void *)self, self.field, self.message];
}

#endif
@end
