// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainDeviceData.h"
#include "nativium/domain/DeviceData.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVDomainDeviceData;

namespace djinni_generated {

struct DeviceData
{
    using CppType = ::nativium::domain::DeviceData;
    using ObjcType = NTVDomainDeviceData*;

    using Boxed = DeviceData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
