// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainResponseError.h"
#include "nativium/domain/ResponseError.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVDomainResponseError;

namespace djinni_generated {

struct ResponseError
{
    using CppType = ::nativium::domain::ResponseError;
    using ObjcType = NTVDomainResponseError*;

    using Boxed = ResponseError;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
