// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface NTVDomainDeviceData : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithUniqueIdentifier:(nonnull NSString *)uniqueIdentifier
                                            name:(nonnull NSString *)name
                                      systemName:(nonnull NSString *)systemName
                                   systemVersion:(nonnull NSString *)systemVersion
                                           model:(nonnull NSString *)model
                                  localizedModel:(nonnull NSString *)localizedModel
                                      appVersion:(nonnull NSString *)appVersion
                                 appShortVersion:(nonnull NSString *)appShortVersion
                                         appName:(nonnull NSString *)appName
                                     screenWidth:(float)screenWidth
                                    screenHeight:(float)screenHeight
                                     screenScale:(float)screenScale
                                    systemOsName:(nonnull NSString *)systemOsName
                                        language:(nonnull NSString *)language
                                            imei:(nonnull NSString *)imei
                                          region:(nonnull NSString *)region NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)deviceDataWithUniqueIdentifier:(nonnull NSString *)uniqueIdentifier
                                                  name:(nonnull NSString *)name
                                            systemName:(nonnull NSString *)systemName
                                         systemVersion:(nonnull NSString *)systemVersion
                                                 model:(nonnull NSString *)model
                                        localizedModel:(nonnull NSString *)localizedModel
                                            appVersion:(nonnull NSString *)appVersion
                                       appShortVersion:(nonnull NSString *)appShortVersion
                                               appName:(nonnull NSString *)appName
                                           screenWidth:(float)screenWidth
                                          screenHeight:(float)screenHeight
                                           screenScale:(float)screenScale
                                          systemOsName:(nonnull NSString *)systemOsName
                                              language:(nonnull NSString *)language
                                                  imei:(nonnull NSString *)imei
                                                region:(nonnull NSString *)region;

@property (nonatomic, readonly, nonnull) NSString * uniqueIdentifier;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSString * systemName;

@property (nonatomic, readonly, nonnull) NSString * systemVersion;

@property (nonatomic, readonly, nonnull) NSString * model;

@property (nonatomic, readonly, nonnull) NSString * localizedModel;

@property (nonatomic, readonly, nonnull) NSString * appVersion;

@property (nonatomic, readonly, nonnull) NSString * appShortVersion;

@property (nonatomic, readonly, nonnull) NSString * appName;

@property (nonatomic, readonly) float screenWidth;

@property (nonatomic, readonly) float screenHeight;

@property (nonatomic, readonly) float screenScale;

@property (nonatomic, readonly, nonnull) NSString * systemOsName;

@property (nonatomic, readonly, nonnull) NSString * language;

@property (nonatomic, readonly, nonnull) NSString * imei;

@property (nonatomic, readonly, nonnull) NSString * region;

@end
