// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainTodo.h"
#include "nativium/domain/Todo.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVDomainTodo;

namespace djinni_generated {

struct Todo
{
    using CppType = ::nativium::domain::Todo;
    using ObjcType = NTVDomainTodo*;

    using Boxed = Todo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
