// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface NTVDomainResponseError : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithField:(nonnull NSString *)field
                              message:(nonnull NSString *)message NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)responseErrorWithField:(nonnull NSString *)field
                                       message:(nonnull NSString *)message;

@property (nonatomic, readonly, nonnull) NSString * field;

@property (nonatomic, readonly, nonnull) NSString * message;

@end
