// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainResponse.h"


@implementation NTVDomainResponse

- (nonnull instancetype)initWithSuccess:(BOOL)success
                                message:(nonnull NSString *)message
                                  error:(nonnull NTVDomainResponseError *)error
                               hasError:(BOOL)hasError
                           httpResponse:(nonnull NTVHttpResponse *)httpResponse
{
    if (self = [super init]) {
        _success = success;
        _message = [message copy];
        _error = error;
        _hasError = hasError;
        _httpResponse = httpResponse;
    }
    return self;
}

+ (nonnull instancetype)responseWithSuccess:(BOOL)success
                                    message:(nonnull NSString *)message
                                      error:(nonnull NTVDomainResponseError *)error
                                   hasError:(BOOL)hasError
                               httpResponse:(nonnull NTVHttpResponse *)httpResponse
{
    return [[self alloc] initWithSuccess:success
                                 message:message
                                   error:error
                                hasError:hasError
                            httpResponse:httpResponse];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p success:%@ message:%@ error:%@ hasError:%@ httpResponse:%@>", self.class, (void *)self, @(self.success), self.message, self.error, @(self.hasError), self.httpResponse];
}

#endif
@end
