// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainInitializationData.h"
#include "nativium/domain/InitializationData.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVDomainInitializationData;

namespace djinni_generated {

struct InitializationData
{
    using CppType = ::nativium::domain::InitializationData;
    using ObjcType = NTVDomainInitializationData*;

    using Boxed = InitializationData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
