// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainResponse.h"
#include "nativium/domain/Response.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVDomainResponse;

namespace djinni_generated {

struct Response
{
    using CppType = ::nativium::domain::Response;
    using ObjcType = NTVDomainResponse*;

    using Boxed = Response;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
