// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainResponseError.h"
#import <Foundation/Foundation.h>

@interface NTVDomainResponse : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithSuccess:(BOOL)success
                                message:(nonnull NSString *)message
                                  error:(nonnull NTVDomainResponseError *)error
                               hasError:(BOOL)hasError NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)responseWithSuccess:(BOOL)success
                                    message:(nonnull NSString *)message
                                      error:(nonnull NTVDomainResponseError *)error
                                   hasError:(BOOL)hasError;

@property (nonatomic, readonly) BOOL success;

@property (nonatomic, readonly, nonnull) NSString * message;

@property (nonatomic, readonly, nonnull) NTVDomainResponseError * error;

@property (nonatomic, readonly) BOOL hasError;

@end
