// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <functional>

namespace nativium { namespace net { namespace http {

enum class HttpMethod : int {
    METHOD_GET = 0,
    METHOD_POST = 1,
    METHOD_HEAD = 2,
    METHOD_PUT = 3,
    METHOD_DELETE = 4,
    METHOD_PATCH = 5,
    METHOD_CONNECT = 6,
    METHOD_OPTIONS = 7,
    METHOD_TRACE = 8,
};

constexpr const char* toString(HttpMethod e) noexcept {
    constexpr const char* names[] = {
        "method_get",
        "method_post",
        "method_head",
        "method_put",
        "method_delete",
        "method_patch",
        "method_connect",
        "method_options",
        "method_trace",
    };
    return names[static_cast<int>(e)];
}

} } }  // namespace nativium::net::http

namespace std {

template <>
struct hash<::nativium::net::http::HttpMethod> {
    size_t operator()(::nativium::net::http::HttpMethod type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
