// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "nativium/net/http/HttpCookie.hpp"
#include "nativium/net/http/HttpHeader.hpp"
#include "nativium/net/http/HttpMethod.hpp"
#include "nativium/net/http/HttpRequestParam.hpp"
#include <string>
#include <utility>
#include <vector>

namespace nativium { namespace net { namespace http {

struct HttpRequest final {
    std::string url;
    HttpMethod method;
    std::vector<HttpRequestParam> params;
    std::vector<HttpHeader> headers;
    std::vector<HttpCookie> cookies;
    std::string body;

    HttpRequest(std::string url_,
                HttpMethod method_,
                std::vector<HttpRequestParam> params_,
                std::vector<HttpHeader> headers_,
                std::vector<HttpCookie> cookies_,
                std::string body_)
    : url(std::move(url_))
    , method(std::move(method_))
    , params(std::move(params_))
    , headers(std::move(headers_))
    , cookies(std::move(cookies_))
    , body(std::move(body_))
    {}
};

} } }  // namespace nativium::net::http
