// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/text/StringHelper.hpp"

namespace djinni_generated {

class NTVStringHelper final : ::djinni::JniInterface<::nativium::text::StringHelper, NTVStringHelper> {
public:
    using CppType = std::shared_ptr<::nativium::text::StringHelper>;
    using CppOptType = std::shared_ptr<::nativium::text::StringHelper>;
    using JniType = jobject;

    using Boxed = NTVStringHelper;

    ~NTVStringHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVStringHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVStringHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVStringHelper();
    friend ::djinni::JniClass<NTVStringHelper>;
    friend ::djinni::JniInterface<::nativium::text::StringHelper, NTVStringHelper>;

};

}  // namespace djinni_generated
