// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export enum HttpMethod {
    METHOD_GET = 0,
    METHOD_POST = 1,
    METHOD_HEAD = 2,
    METHOD_PUT = 3,
    METHOD_DELETE = 4,
    METHOD_PATCH = 5,
    METHOD_CONNECT = 6,
    METHOD_OPTIONS = 7,
    METHOD_TRACE = 8,
}

export interface /*record*/ HttpHeader {
    name: string;
    value: string;
}

export interface /*record*/ HttpResponse {
    code: number;
    body: string;
    url: string;
    headers: Array<HttpHeader>;
    cookies: Array<HttpCookie>;
}

export interface /*record*/ HttpRequestParam {
    name: string;
    value: string;
}

export interface /*record*/ HttpCookie {
    name: string;
    value: string;
}

export interface /*record*/ HttpRequest {
    url: string;
    method: HttpMethod;
    params: Array<HttpRequestParam>;
    headers: Array<HttpHeader>;
    cookies: Array<HttpCookie>;
    body: string;
}

export interface HttpClientPlatformService {
    doRequest(request: HttpRequest): HttpResponse;
}

export interface HttpClientLogger {
    onRequest(request: HttpRequest): void;
    onResponse(request: HttpRequest, response: HttpResponse): void;
}

export interface HttpClient {
    setPlatformService(ps: HttpClientPlatformService): void;
    getPlatformService(): HttpClientPlatformService;
    hasPlatformService(): boolean;
    doRequest(request: HttpRequest): HttpResponse;
    setLogger(logger: HttpClientLogger): void;
    getLogger(): HttpClientLogger;
    hasLogger(): boolean;
}
export interface HttpClient_statics {
    shared(): HttpClient;
}

export interface HttpClient_statics {
    HttpClient: HttpClient_statics;
}
