// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpResponse.h"


@implementation NTVHttpResponse

- (nonnull instancetype)initWithCode:(int32_t)code
                                body:(nonnull NSString *)body
                                 url:(nonnull NSString *)url
                             headers:(nonnull NSArray<NTVHttpHeader *> *)headers
                             cookies:(nonnull NSArray<NTVHttpCookie *> *)cookies
{
    if (self = [super init]) {
        _code = code;
        _body = [body copy];
        _url = [url copy];
        _headers = [headers copy];
        _cookies = [cookies copy];
    }
    return self;
}

+ (nonnull instancetype)httpResponseWithCode:(int32_t)code
                                        body:(nonnull NSString *)body
                                         url:(nonnull NSString *)url
                                     headers:(nonnull NSArray<NTVHttpHeader *> *)headers
                                     cookies:(nonnull NSArray<NTVHttpCookie *> *)cookies
{
    return [[self alloc] initWithCode:code
                                 body:body
                                  url:url
                              headers:headers
                              cookies:cookies];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p code:%@ body:%@ url:%@ headers:%@ cookies:%@>", self.class, (void *)self, @(self.code), self.body, self.url, self.headers, self.cookies];
}

#endif
@end
