// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpRequest.h"
#import "nativium/net/http/NTVHttpResponse.h"
#import <Foundation/Foundation.h>


@protocol NTVHttpClientPlatformService

- (nonnull NTVHttpResponse *)doRequest:(nonnull NTVHttpRequest *)request;

@end
