// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpRequest+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "nativium/net/http/NTVHttpCookie+Private.h"
#import "nativium/net/http/NTVHttpHeader+Private.h"
#import "nativium/net/http/NTVHttpMethod+Private.h"
#import "nativium/net/http/NTVHttpRequestParam+Private.h"
#include <cassert>

namespace djinni_generated {

auto HttpRequest::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.url),
            ::djinni::Enum<::nativium::net::http::HttpMethod, NTVHttpMethod>::toCpp(obj.method),
            ::djinni::List<::djinni_generated::HttpRequestParam>::toCpp(obj.params),
            ::djinni::List<::djinni_generated::HttpHeader>::toCpp(obj.headers),
            ::djinni::List<::djinni_generated::HttpCookie>::toCpp(obj.cookies),
            ::djinni::String::toCpp(obj.body)};
}

auto HttpRequest::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NTVHttpRequest alloc] initWithUrl:(::djinni::String::fromCpp(cpp.url))
                                        method:(::djinni::Enum<::nativium::net::http::HttpMethod, NTVHttpMethod>::fromCpp(cpp.method))
                                        params:(::djinni::List<::djinni_generated::HttpRequestParam>::fromCpp(cpp.params))
                                       headers:(::djinni::List<::djinni_generated::HttpHeader>::fromCpp(cpp.headers))
                                       cookies:(::djinni::List<::djinni_generated::HttpCookie>::fromCpp(cpp.cookies))
                                          body:(::djinni::String::fromCpp(cpp.body))];
}

}  // namespace djinni_generated
