// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/net/http/HttpClientLogger.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVHttpClientLogger;

namespace djinni_generated {

class HttpClientLogger
{
public:
    using CppType = std::shared_ptr<::nativium::net::http::HttpClientLogger>;
    using CppOptType = std::shared_ptr<::nativium::net::http::HttpClientLogger>;
    using ObjcType = NTVHttpClientLogger*;

    using Boxed = HttpClientLogger;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

