// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpRequest.h"
#import "nativium/net/http/NTVHttpResponse.h"
#import <Foundation/Foundation.h>
@class NTVHttpClient;
@class NTVHttpClientLogger;
@protocol NTVHttpClientPlatformService;


@interface NTVHttpClient : NSObject

+ (nullable NTVHttpClient *)shared;

- (void)setPlatformService:(nullable id<NTVHttpClientPlatformService>)ps;

- (nullable id<NTVHttpClientPlatformService>)getPlatformService;

- (BOOL)hasPlatformService;

- (nonnull NTVHttpResponse *)doRequest:(nonnull NTVHttpRequest *)request;

- (void)setLogger:(nullable NTVHttpClientLogger *)logger;

- (nullable NTVHttpClientLogger *)getLogger;

- (BOOL)hasLogger;

@end
