// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpCookie.h"


@implementation NTVHttpCookie

- (nonnull instancetype)initWithName:(nonnull NSString *)name
                               value:(nonnull NSString *)value
{
    if (self = [super init]) {
        _name = [name copy];
        _value = [value copy];
    }
    return self;
}

+ (nonnull instancetype)httpCookieWithName:(nonnull NSString *)name
                                     value:(nonnull NSString *)value
{
    return [[self alloc] initWithName:name
                                value:value];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p name:%@ value:%@>", self.class, (void *)self, self.name, self.value];
}

#endif
@end
