// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/net/http/HttpClient.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVHttpClient;

namespace djinni_generated {

class HttpClient
{
public:
    using CppType = std::shared_ptr<::nativium::net::http::HttpClient>;
    using CppOptType = std::shared_ptr<::nativium::net::http::HttpClient>;
    using ObjcType = NTVHttpClient*;

    using Boxed = HttpClient;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

