// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpCookie.h"
#include "nativium/net/http/HttpCookie.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVHttpCookie;

namespace djinni_generated {

struct HttpCookie
{
    using CppType = ::nativium::net::http::HttpCookie;
    using ObjcType = NTVHttpCookie*;

    using Boxed = HttpCookie;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
