// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainCustomer.h"
#import <Foundation/Foundation.h>


@interface NTVHelperCustomerHelper : NSObject

+ (BOOL)isLogged;

+ (nonnull NSString *)getToken;

+ (nonnull NTVDomainCustomer *)create;

+ (void)onCustomerLogin:(nonnull NTVDomainCustomer *)customer;

@end
