// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>


@interface NTVHelperSecurityHelper : NSObject

+ (nonnull NSString *)generateUuidV4;

+ (nonnull NSString *)generateHash:(nonnull NSString *)algorithm
                             value:(nonnull NSString *)value;

@end
