// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/helper/CustomerHelper.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVHelperCustomerHelper;

namespace djinni_generated {

class CustomerHelper
{
public:
    using CppType = std::shared_ptr<::nativium::helper::CustomerHelper>;
    using CppOptType = std::shared_ptr<::nativium::helper::CustomerHelper>;
    using ObjcType = NTVHelperCustomerHelper*;

    using Boxed = CustomerHelper;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

