// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainTodo.h"
#import <Foundation/Foundation.h>


@interface NTVHelperTodoHelper : NSObject

+ (nonnull NTVDomainTodo *)create;

@end
