// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/domain/NTVDomainCustomer.h"
#import <Foundation/Foundation.h>


@interface NTVHelperSharedDataHelper : NSObject

+ (void)setCustomer:(nonnull NTVDomainCustomer *)value;

+ (nonnull NTVDomainCustomer *)getCustomer;

+ (void)storeCustomer;

+ (void)setDemoFlag:(BOOL)value;

+ (BOOL)getDemoFlag;

@end
