// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>


@interface NTVHelperEnvironmentHelper : NSObject

+ (nonnull NSString *)getSecretKey;

@end
