// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/helper/NTVStringHelper.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVStringHelper::NTVStringHelper() : ::djinni::JniInterface<::nativium::helper::StringHelper, NTVStringHelper>("com/nativium/helper/StringHelper$CppProxy") {}

NTVStringHelper::~NTVStringHelper() = default;


CJNIEXPORT void JNICALL Java_com_nativium_helper_StringHelper_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::nativium::helper::StringHelper>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_nativium_helper_StringHelper_trim(JNIEnv* jniEnv, jobject /*this*/, jstring j_value)
{
    try {
        auto r = ::nativium::helper::StringHelper::trim(::djinni::String::toCpp(jniEnv, j_value));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_nativium_helper_StringHelper_leftTrim(JNIEnv* jniEnv, jobject /*this*/, jstring j_value)
{
    try {
        auto r = ::nativium::helper::StringHelper::leftTrim(::djinni::String::toCpp(jniEnv, j_value));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_nativium_helper_StringHelper_rightTrim(JNIEnv* jniEnv, jobject /*this*/, jstring j_value)
{
    try {
        auto r = ::nativium::helper::StringHelper::rightTrim(::djinni::String::toCpp(jniEnv, j_value));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_nativium_helper_StringHelper_toLower(JNIEnv* jniEnv, jobject /*this*/, jstring j_value)
{
    try {
        auto r = ::nativium::helper::StringHelper::toLower(::djinni::String::toCpp(jniEnv, j_value));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_nativium_helper_StringHelper_toUpper(JNIEnv* jniEnv, jobject /*this*/, jstring j_value)
{
    try {
        auto r = ::nativium::helper::StringHelper::toUpper(::djinni::String::toCpp(jniEnv, j_value));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_nativium_helper_StringHelper_split(JNIEnv* jniEnv, jobject /*this*/, jstring j_text, jstring j_sep, jboolean j_trimEmpty)
{
    try {
        auto r = ::nativium::helper::StringHelper::split(::djinni::String::toCpp(jniEnv, j_text),
                                                         ::djinni::String::toCpp(jniEnv, j_sep),
                                                         ::djinni::Bool::toCpp(jniEnv, j_trimEmpty));
        return ::djinni::release(::djinni::List<::djinni::String>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
