// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export interface SharedDataPlatformService {
    setString(groupName: string, key: string, value: string): void;
    setInteger(groupName: string, key: string, value: number): void;
    setLong(groupName: string, key: string, value: bigint): void;
    setBool(groupName: string, key: string, value: boolean): void;
    setFloat(groupName: string, key: string, value: number): void;
    setDouble(groupName: string, key: string, value: number): void;
    getString(groupName: string, key: string): string;
    getInteger(groupName: string, key: string): number;
    getLong(groupName: string, key: string): bigint;
    getBool(groupName: string, key: string): boolean;
    getFloat(groupName: string, key: string): number;
    getDouble(groupName: string, key: string): number;
    getStringWithDefaultValue(groupName: string, key: string, defaultValue: string): string;
    getIntegerWithDefaultValue(groupName: string, key: string, defaultValue: number): number;
    getLongWithDefaultValue(groupName: string, key: string, defaultValue: bigint): bigint;
    getBoolWithDefaultValue(groupName: string, key: string, defaultValue: boolean): boolean;
    getFloatWithDefaultValue(groupName: string, key: string, defaultValue: number): number;
    getDoubleWithDefaultValue(groupName: string, key: string, defaultValue: number): number;
    has(groupName: string, key: string): boolean;
    remove(groupName: string, key: string): void;
    clear(groupName: string): void;
}

export interface SharedData {
    setPlatformService(ps: SharedDataPlatformService): void;
    getPlatformService(): SharedDataPlatformService;
    hasPlatformService(): boolean;
    setString(groupName: string, key: string, value: string): void;
    setInteger(groupName: string, key: string, value: number): void;
    setLong(groupName: string, key: string, value: bigint): void;
    setBool(groupName: string, key: string, value: boolean): void;
    setFloat(groupName: string, key: string, value: number): void;
    setDouble(groupName: string, key: string, value: number): void;
    getString(groupName: string, key: string): string;
    getInteger(groupName: string, key: string): number;
    getLong(groupName: string, key: string): bigint;
    getBool(groupName: string, key: string): boolean;
    getFloat(groupName: string, key: string): number;
    getDouble(groupName: string, key: string): number;
    getStringWithDefaultValue(groupName: string, key: string, defaultValue: string): string;
    getIntegerWithDefaultValue(groupName: string, key: string, defaultValue: number): number;
    getLongWithDefaultValue(groupName: string, key: string, defaultValue: bigint): bigint;
    getBoolWithDefaultValue(groupName: string, key: string, defaultValue: boolean): boolean;
    getFloatWithDefaultValue(groupName: string, key: string, defaultValue: number): number;
    getDoubleWithDefaultValue(groupName: string, key: string, defaultValue: number): number;
    has(groupName: string, key: string): boolean;
    remove(groupName: string, key: string): void;
    clear(groupName: string): void;
}
export interface SharedData_statics {
    shared(): SharedData;
}

export interface SharedData_statics {
    SharedData: SharedData_statics;
}
