// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/net/http/HttpRequest.hpp"

namespace djinni_generated {

class NTVHttpRequest final {
public:
    using CppType = ::nativium::net::http::HttpRequest;
    using JniType = jobject;

    using Boxed = NTVHttpRequest;

    ~NTVHttpRequest();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NTVHttpRequest();
    friend ::djinni::JniClass<NTVHttpRequest>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nativium/net/http/HttpRequest") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Lcom/nativium/net/http/HttpMethod;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/lang/String;)V") };
    const jfieldID field_mUrl { ::djinni::jniGetFieldID(clazz.get(), "mUrl", "Ljava/lang/String;") };
    const jfieldID field_mMethod { ::djinni::jniGetFieldID(clazz.get(), "mMethod", "Lcom/nativium/net/http/HttpMethod;") };
    const jfieldID field_mParams { ::djinni::jniGetFieldID(clazz.get(), "mParams", "Ljava/util/ArrayList;") };
    const jfieldID field_mHeaders { ::djinni::jniGetFieldID(clazz.get(), "mHeaders", "Ljava/util/ArrayList;") };
    const jfieldID field_mCookies { ::djinni::jniGetFieldID(clazz.get(), "mCookies", "Ljava/util/ArrayList;") };
    const jfieldID field_mBody { ::djinni::jniGetFieldID(clazz.get(), "mBody", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
