// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/net/http/NTVHttpClientLogger.hpp"  // my header
#include "com/nativium/net/http/NTVHttpRequest.hpp"
#include "com/nativium/net/http/NTVHttpResponse.hpp"

namespace djinni_generated {

NTVHttpClientLogger::NTVHttpClientLogger() : ::djinni::JniInterface<::nativium::net::http::HttpClientLogger, NTVHttpClientLogger>("com/nativium/net/http/HttpClientLogger$CppProxy") {}

NTVHttpClientLogger::~NTVHttpClientLogger() = default;


CJNIEXPORT void JNICALL Java_com_nativium_net_http_HttpClientLogger_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::nativium::net::http::HttpClientLogger>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nativium_net_http_HttpClientLogger_00024CppProxy_native_1onRequest(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_request)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::nativium::net::http::HttpClientLogger>(nativeRef);
        ref->onRequest(::djinni_generated::NTVHttpRequest::toCpp(jniEnv, j_request));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nativium_net_http_HttpClientLogger_00024CppProxy_native_1onResponse(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_request, jobject j_response)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::nativium::net::http::HttpClientLogger>(nativeRef);
        ref->onResponse(::djinni_generated::NTVHttpRequest::toCpp(jniEnv, j_request),
                        ::djinni_generated::NTVHttpResponse::toCpp(jniEnv, j_response));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
