// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/net/http/HttpClient.hpp"

namespace djinni_generated {

class NTVHttpClient final : ::djinni::JniInterface<::nativium::net::http::HttpClient, NTVHttpClient> {
public:
    using CppType = std::shared_ptr<::nativium::net::http::HttpClient>;
    using CppOptType = std::shared_ptr<::nativium::net::http::HttpClient>;
    using JniType = jobject;

    using Boxed = NTVHttpClient;

    ~NTVHttpClient();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVHttpClient>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVHttpClient>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVHttpClient();
    friend ::djinni::JniClass<NTVHttpClient>;
    friend ::djinni::JniInterface<::nativium::net::http::HttpClient, NTVHttpClient>;

};

}  // namespace djinni_generated
