// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/net/http/HttpClientLogger.hpp"

namespace djinni_generated {

class NTVHttpClientLogger final : ::djinni::JniInterface<::nativium::net::http::HttpClientLogger, NTVHttpClientLogger> {
public:
    using CppType = std::shared_ptr<::nativium::net::http::HttpClientLogger>;
    using CppOptType = std::shared_ptr<::nativium::net::http::HttpClientLogger>;
    using JniType = jobject;

    using Boxed = NTVHttpClientLogger;

    ~NTVHttpClientLogger();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVHttpClientLogger>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVHttpClientLogger>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVHttpClientLogger();
    friend ::djinni::JniClass<NTVHttpClientLogger>;
    friend ::djinni::JniInterface<::nativium::net::http::HttpClientLogger, NTVHttpClientLogger>;

};

}  // namespace djinni_generated
