// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/net/http/HttpClientPlatformService.hpp"

namespace djinni_generated {

class NTVHttpClientPlatformService final : ::djinni::JniInterface<::nativium::net::http::HttpClientPlatformService, NTVHttpClientPlatformService> {
public:
    using CppType = std::shared_ptr<::nativium::net::http::HttpClientPlatformService>;
    using CppOptType = std::shared_ptr<::nativium::net::http::HttpClientPlatformService>;
    using JniType = jobject;

    using Boxed = NTVHttpClientPlatformService;

    ~NTVHttpClientPlatformService();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVHttpClientPlatformService>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVHttpClientPlatformService>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVHttpClientPlatformService();
    friend ::djinni::JniClass<NTVHttpClientPlatformService>;
    friend ::djinni::JniInterface<::nativium::net::http::HttpClientPlatformService, NTVHttpClientPlatformService>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::nativium::net::http::HttpClientPlatformService
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        ::nativium::net::http::HttpResponse doRequest(const ::nativium::net::http::HttpRequest & request) override;

    private:
        friend ::djinni::JniInterface<::nativium::net::http::HttpClientPlatformService, ::djinni_generated::NTVHttpClientPlatformService>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nativium/net/http/HttpClientPlatformService") };
    const jmethodID method_doRequest { ::djinni::jniGetMethodID(clazz.get(), "doRequest", "(Lcom/nativium/net/http/HttpRequest;)Lcom/nativium/net/http/HttpResponse;") };
};

}  // namespace djinni_generated
