// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/net/http/NTVHttpRequest.hpp"  // my header
#include "com/nativium/net/http/NTVHttpCookie.hpp"
#include "com/nativium/net/http/NTVHttpHeader.hpp"
#include "com/nativium/net/http/NTVHttpMethod.hpp"
#include "com/nativium/net/http/NTVHttpRequestParam.hpp"
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVHttpRequest::NTVHttpRequest() = default;

NTVHttpRequest::~NTVHttpRequest() = default;

auto NTVHttpRequest::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NTVHttpRequest>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.url)),
                                                           ::djinni::get(::djinni_generated::NTVHttpMethod::fromCpp(jniEnv, c.method)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::NTVHttpRequestParam>::fromCpp(jniEnv, c.params)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::NTVHttpHeader>::fromCpp(jniEnv, c.headers)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::NTVHttpCookie>::fromCpp(jniEnv, c.cookies)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.body)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NTVHttpRequest::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NTVHttpRequest>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mUrl)),
            ::djinni_generated::NTVHttpMethod::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mMethod)),
            ::djinni::List<::djinni_generated::NTVHttpRequestParam>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mParams)),
            ::djinni::List<::djinni_generated::NTVHttpHeader>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mHeaders)),
            ::djinni::List<::djinni_generated::NTVHttpCookie>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mCookies)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mBody))};
}

}  // namespace djinni_generated
