// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/net/http/HttpRequestParam.hpp"

namespace djinni_generated {

class NTVHttpRequestParam final {
public:
    using CppType = ::nativium::net::http::HttpRequestParam;
    using JniType = jobject;

    using Boxed = NTVHttpRequestParam;

    ~NTVHttpRequestParam();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NTVHttpRequestParam();
    friend ::djinni::JniClass<NTVHttpRequestParam>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nativium/net/http/HttpRequestParam") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
    const jfieldID field_mValue { ::djinni::jniGetFieldID(clazz.get(), "mValue", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
