// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/io/FileHelperPlatformService.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol NTVFileHelperPlatformService;

namespace djinni_generated {

class FileHelperPlatformService
{
public:
    using CppType = std::shared_ptr<::nativium::io::FileHelperPlatformService>;
    using CppOptType = std::shared_ptr<::nativium::io::FileHelperPlatformService>;
    using ObjcType = id<NTVFileHelperPlatformService>;

    using Boxed = FileHelperPlatformService;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

