// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export interface /*record*/ HttpServerConfig {
    port: number;
    staticPath: string;
}

export interface HttpServer {
    initialize(config: HttpServerConfig): void;
    getConfig(): HttpServerConfig;
    start(): void;
    stop(): void;
    waitForTermination(): void;
    getSocketPort(): number;
    getSocketHost(): string;
    getSocketAddress(): string;
    isSocketSecure(): boolean;
    isRunning(): boolean;
}
export interface HttpServer_statics {
    shared(): HttpServer;
}

export interface HttpServer_statics {
    HttpServer: HttpServer_statics;
}
