// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

import { CustomerStatusEnum } from "./app-enumerator"
import { HttpResponse } from "./http-client"

export interface /*record*/ Response {
    success: boolean;
    message: string;
    error: ResponseError;
    hasError: boolean;
    httpResponse: HttpResponse;
}

export interface /*record*/ ResponseError {
    field: string;
    message: string;
}

export interface /*record*/ Todo {
    id: bigint;
    title: string;
    body: string;
    data: Map<string, string>;
    done: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface /*record*/ Customer {
    id: bigint;
    name: string;
    token: string;
    status: CustomerStatusEnum;
}

export interface /*record*/ InitializationData {
    appId: string;
    name: string;
    basePath: string;
    databaseMigrationMaxVersion: number;
    debug: boolean;
}

export interface /*record*/ DeviceData {
    uniqueIdentifier: string;
    name: string;
    systemName: string;
    systemVersion: string;
    model: string;
    localizedModel: string;
    appVersion: string;
    appShortVersion: string;
    appName: string;
    screenWidth: number;
    screenHeight: number;
    screenScale: number;
    systemOsName: string;
    language: string;
    imei: string;
    region: string;
}

export interface AppDomain_statics {
}
