// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/domain/NTVDomainResponse.hpp"  // my header
#include "com/nativium/domain/NTVDomainResponseError.hpp"
#include "com/nativium/net/http/NTVHttpResponse.hpp"
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVDomainResponse::NTVDomainResponse() = default;

NTVDomainResponse::~NTVDomainResponse() = default;

auto NTVDomainResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NTVDomainResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.success)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.message)),
                                                           ::djinni::get(::djinni_generated::NTVDomainResponseError::fromCpp(jniEnv, c.error)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.hasError)),
                                                           ::djinni::get(::djinni_generated::NTVHttpResponse::fromCpp(jniEnv, c.httpResponse)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NTVDomainResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NTVDomainResponse>::get();
    return {::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mSuccess)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mMessage)),
            ::djinni_generated::NTVDomainResponseError::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mError)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mHasError)),
            ::djinni_generated::NTVHttpResponse::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mHttpResponse))};
}

}  // namespace djinni_generated
