// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/net/http/HttpServerConfig.hpp"

namespace djinni_generated {

struct NTVHttpServerConfig
{
    using CppType = ::nativium::net::http::HttpServerConfig;
    using JsType = em::val;
    using Boxed = NTVHttpServerConfig;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
