// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.net.http;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class HttpClientLogger {
    public abstract void onRequest(HttpRequest request);

    public abstract void onResponse(HttpRequest request, HttpResponse response);

    public static final class CppProxy extends HttpClientLogger
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public void onRequest(HttpRequest request)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onRequest(this.nativeRef, request);
        }
        private native void native_onRequest(long _nativeRef, HttpRequest request);

        @Override
        public void onResponse(HttpRequest request, HttpResponse response)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onResponse(this.nativeRef, request, response);
        }
        private native void native_onResponse(long _nativeRef, HttpRequest request, HttpResponse response);
    }
}
