// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/helper/CustomerHelper.hpp"

namespace djinni_generated {

struct NTVHelperCustomerHelper : ::djinni::JsInterface<::nativium::helper::CustomerHelper, NTVHelperCustomerHelper> {
    using CppType = std::shared_ptr<::nativium::helper::CustomerHelper>;
    using CppOptType = std::shared_ptr<::nativium::helper::CustomerHelper>;
    using JsType = em::val;
    using Boxed = NTVHelperCustomerHelper;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        djinni::checkForNull(c.get(), "NTVHelperCustomerHelper::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static bool isLogged();
    static std::string getToken();
    static em::val create();
    static void onCustomerLogin(const em::val& w_customer);

};

}  // namespace djinni_generated
