// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/helper/SecurityHelper.hpp"

namespace djinni_generated {

struct NTVHelperSecurityHelper : ::djinni::JsInterface<::nativium::helper::SecurityHelper, NTVHelperSecurityHelper> {
    using CppType = std::shared_ptr<::nativium::helper::SecurityHelper>;
    using CppOptType = std::shared_ptr<::nativium::helper::SecurityHelper>;
    using JsType = em::val;
    using Boxed = NTVHelperSecurityHelper;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        djinni::checkForNull(c.get(), "NTVHelperSecurityHelper::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static std::string generateUuidV4();

};

}  // namespace djinni_generated
