// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/helper/EnvironmentHelper.hpp"

namespace djinni_generated {

struct NTVHelperEnvironmentHelper : ::djinni::JsInterface<::nativium::helper::EnvironmentHelper, NTVHelperEnvironmentHelper> {
    using CppType = std::shared_ptr<::nativium::helper::EnvironmentHelper>;
    using CppOptType = std::shared_ptr<::nativium::helper::EnvironmentHelper>;
    using JsType = em::val;
    using Boxed = NTVHelperEnvironmentHelper;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        djinni::checkForNull(c.get(), "NTVHelperEnvironmentHelper::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static std::string getSecretKey();

};

}  // namespace djinni_generated
