// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/helper/NTVHelperCustomerHelper.hpp"  // my header
#include "nativium/domain/NTVDomainCustomer.hpp"

namespace djinni_generated {

em::val NTVHelperCustomerHelper::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

bool NTVHelperCustomerHelper::isLogged() {
    try {
        auto r = ::nativium::helper::CustomerHelper::isLogged();
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}
std::string NTVHelperCustomerHelper::getToken() {
    try {
        auto r = ::nativium::helper::CustomerHelper::getToken();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
em::val NTVHelperCustomerHelper::create() {
    try {
        auto r = ::nativium::helper::CustomerHelper::create();
        return ::djinni_generated::NTVDomainCustomer::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni_generated::NTVDomainCustomer>::handleNativeException(e);
    }
}
void NTVHelperCustomerHelper::onCustomerLogin(const em::val& w_customer) {
    try {
        ::nativium::helper::CustomerHelper::onCustomerLogin(::djinni_generated::NTVDomainCustomer::toCpp(w_customer));
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(nativium_helper_customer_helper) {
    em::class_<::nativium::helper::CustomerHelper>("CustomerHelper")
        .smart_ptr<std::shared_ptr<::nativium::helper::CustomerHelper>>("CustomerHelper")
        .function("nativeDestroy", &NTVHelperCustomerHelper::nativeDestroy)
        .class_function("isLogged", NTVHelperCustomerHelper::isLogged)
        .class_function("getToken", NTVHelperCustomerHelper::getToken)
        .class_function("create", NTVHelperCustomerHelper::create)
        .class_function("onCustomerLogin", NTVHelperCustomerHelper::onCustomerLogin)
        ;
}

}  // namespace djinni_generated
