// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/helper/NTVHelperSharedDataHelper.hpp"  // my header
#include "nativium/domain/NTVDomainCustomer.hpp"

namespace djinni_generated {

em::val NTVHelperSharedDataHelper::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

void NTVHelperSharedDataHelper::setCustomer(const em::val& w_value) {
    try {
        ::nativium::helper::SharedDataHelper::setCustomer(::djinni_generated::NTVDomainCustomer::toCpp(w_value));
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
em::val NTVHelperSharedDataHelper::getCustomer() {
    try {
        auto r = ::nativium::helper::SharedDataHelper::getCustomer();
        return ::djinni_generated::NTVDomainCustomer::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni_generated::NTVDomainCustomer>::handleNativeException(e);
    }
}
void NTVHelperSharedDataHelper::storeCustomer() {
    try {
        ::nativium::helper::SharedDataHelper::storeCustomer();
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
void NTVHelperSharedDataHelper::setDemoFlag(bool w_value) {
    try {
        ::nativium::helper::SharedDataHelper::setDemoFlag(::djinni::Bool::toCpp(w_value));
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
bool NTVHelperSharedDataHelper::getDemoFlag() {
    try {
        auto r = ::nativium::helper::SharedDataHelper::getDemoFlag();
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(nativium_helper_shared_data_helper) {
    em::class_<::nativium::helper::SharedDataHelper>("SharedDataHelper")
        .smart_ptr<std::shared_ptr<::nativium::helper::SharedDataHelper>>("SharedDataHelper")
        .function("nativeDestroy", &NTVHelperSharedDataHelper::nativeDestroy)
        .class_function("setCustomer", NTVHelperSharedDataHelper::setCustomer)
        .class_function("getCustomer", NTVHelperSharedDataHelper::getCustomer)
        .class_function("storeCustomer", NTVHelperSharedDataHelper::storeCustomer)
        .class_function("setDemoFlag", NTVHelperSharedDataHelper::setDemoFlag)
        .class_function("getDemoFlag", NTVHelperSharedDataHelper::getDemoFlag)
        ;
}

}  // namespace djinni_generated
