// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/domain/Customer.hpp"

namespace djinni_generated {

struct NTVDomainCustomer
{
    using CppType = ::nativium::domain::Customer;
    using JsType = em::val;
    using Boxed = NTVDomainCustomer;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
