// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/domain/NTVDomainTodo.hpp"  // my header

namespace djinni_generated {

auto NTVDomainTodo::toCpp(const JsType& j) -> CppType {
    return {::djinni::I64::Boxed::toCpp(j["id"]),
            ::djinni::String::Boxed::toCpp(j["title"]),
            ::djinni::String::Boxed::toCpp(j["body"]),
            ::djinni::Map<::djinni::String, ::djinni::String>::Boxed::toCpp(j["data"]),
            ::djinni::Bool::Boxed::toCpp(j["done"]),
            ::djinni::Date::Boxed::toCpp(j["createdAt"]),
            ::djinni::Date::Boxed::toCpp(j["updatedAt"])};
}
auto NTVDomainTodo::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::I64::Boxed::fromCpp(c.id));
    js.set("title", ::djinni::String::Boxed::fromCpp(c.title));
    js.set("body", ::djinni::String::Boxed::fromCpp(c.body));
    js.set("data", ::djinni::Map<::djinni::String, ::djinni::String>::Boxed::fromCpp(c.data));
    js.set("done", ::djinni::Bool::Boxed::fromCpp(c.done));
    js.set("createdAt", ::djinni::Date::Boxed::fromCpp(c.createdAt));
    js.set("updatedAt", ::djinni::Date::Boxed::fromCpp(c.updatedAt));
    return js;
}

}  // namespace djinni_generated
