// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/domain/NTVDomainDeviceData.hpp"  // my header

namespace djinni_generated {

auto NTVDomainDeviceData::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["uniqueIdentifier"]),
            ::djinni::String::Boxed::toCpp(j["name"]),
            ::djinni::String::Boxed::toCpp(j["systemName"]),
            ::djinni::String::Boxed::toCpp(j["systemVersion"]),
            ::djinni::String::Boxed::toCpp(j["model"]),
            ::djinni::String::Boxed::toCpp(j["localizedModel"]),
            ::djinni::String::Boxed::toCpp(j["appVersion"]),
            ::djinni::String::Boxed::toCpp(j["appShortVersion"]),
            ::djinni::String::Boxed::toCpp(j["appName"]),
            ::djinni::F32::Boxed::toCpp(j["screenWidth"]),
            ::djinni::F32::Boxed::toCpp(j["screenHeight"]),
            ::djinni::F32::Boxed::toCpp(j["screenScale"]),
            ::djinni::String::Boxed::toCpp(j["systemOsName"]),
            ::djinni::String::Boxed::toCpp(j["language"]),
            ::djinni::String::Boxed::toCpp(j["imei"]),
            ::djinni::String::Boxed::toCpp(j["region"])};
}
auto NTVDomainDeviceData::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("uniqueIdentifier", ::djinni::String::Boxed::fromCpp(c.uniqueIdentifier));
    js.set("name", ::djinni::String::Boxed::fromCpp(c.name));
    js.set("systemName", ::djinni::String::Boxed::fromCpp(c.systemName));
    js.set("systemVersion", ::djinni::String::Boxed::fromCpp(c.systemVersion));
    js.set("model", ::djinni::String::Boxed::fromCpp(c.model));
    js.set("localizedModel", ::djinni::String::Boxed::fromCpp(c.localizedModel));
    js.set("appVersion", ::djinni::String::Boxed::fromCpp(c.appVersion));
    js.set("appShortVersion", ::djinni::String::Boxed::fromCpp(c.appShortVersion));
    js.set("appName", ::djinni::String::Boxed::fromCpp(c.appName));
    js.set("screenWidth", ::djinni::F32::Boxed::fromCpp(c.screenWidth));
    js.set("screenHeight", ::djinni::F32::Boxed::fromCpp(c.screenHeight));
    js.set("screenScale", ::djinni::F32::Boxed::fromCpp(c.screenScale));
    js.set("systemOsName", ::djinni::String::Boxed::fromCpp(c.systemOsName));
    js.set("language", ::djinni::String::Boxed::fromCpp(c.language));
    js.set("imei", ::djinni::String::Boxed::fromCpp(c.imei));
    js.set("region", ::djinni::String::Boxed::fromCpp(c.region));
    return js;
}

}  // namespace djinni_generated
