// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/domain/NTVDomainResponseError.hpp"  // my header

namespace djinni_generated {

auto NTVDomainResponseError::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["field"]),
            ::djinni::String::Boxed::toCpp(j["message"])};
}
auto NTVDomainResponseError::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("field", ::djinni::String::Boxed::fromCpp(c.field));
    js.set("message", ::djinni::String::Boxed::fromCpp(c.message));
    return js;
}

}  // namespace djinni_generated
