// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/domain/Response.hpp"

namespace djinni_generated {

struct NTVDomainResponse
{
    using CppType = ::nativium::domain::Response;
    using JsType = em::val;
    using Boxed = NTVDomainResponse;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
