// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/domain/InitializationData.hpp"

namespace djinni_generated {

struct NTVDomainInitializationData
{
    using CppType = ::nativium::domain::InitializationData;
    using JsType = em::val;
    using Boxed = NTVDomainInitializationData;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
