// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/helper/NTVHelperEnvironmentHelper.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVHelperEnvironmentHelper::NTVHelperEnvironmentHelper() : ::djinni::JniInterface<::nativium::helper::EnvironmentHelper, NTVHelperEnvironmentHelper>("com/nativium/helper/EnvironmentHelper$CppProxy") {}

NTVHelperEnvironmentHelper::~NTVHelperEnvironmentHelper() = default;


CJNIEXPORT void JNICALL Java_com_nativium_helper_EnvironmentHelper_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::nativium::helper::EnvironmentHelper>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_nativium_helper_EnvironmentHelper_getSecretKey(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::nativium::helper::EnvironmentHelper::getSecretKey();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
