// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/helper/NTVHelperTodoHelper.hpp"  // my header
#include "com/nativium/domain/NTVDomainTodo.hpp"

namespace djinni_generated {

NTVHelperTodoHelper::NTVHelperTodoHelper() : ::djinni::JniInterface<::nativium::helper::TodoHelper, NTVHelperTodoHelper>("com/nativium/helper/TodoHelper$CppProxy") {}

NTVHelperTodoHelper::~NTVHelperTodoHelper() = default;


CJNIEXPORT void JNICALL Java_com_nativium_helper_TodoHelper_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::nativium::helper::TodoHelper>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT ::djinni_generated::NTVDomainTodo::JniType JNICALL Java_com_nativium_helper_TodoHelper_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::nativium::helper::TodoHelper::create();
        return ::djinni::release(::djinni_generated::NTVDomainTodo::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
