// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/helper/NTVHelperSharedDataHelper.hpp"  // my header
#include "com/nativium/domain/NTVDomainCustomer.hpp"
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVHelperSharedDataHelper::NTVHelperSharedDataHelper() : ::djinni::JniInterface<::nativium::helper::SharedDataHelper, NTVHelperSharedDataHelper>("com/nativium/helper/SharedDataHelper$CppProxy") {}

NTVHelperSharedDataHelper::~NTVHelperSharedDataHelper() = default;


CJNIEXPORT void JNICALL Java_com_nativium_helper_SharedDataHelper_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::nativium::helper::SharedDataHelper>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nativium_helper_SharedDataHelper_setCustomer(JNIEnv* jniEnv, jobject /*this*/, ::djinni_generated::NTVDomainCustomer::JniType j_value)
{
    try {
        ::nativium::helper::SharedDataHelper::setCustomer(::djinni_generated::NTVDomainCustomer::toCpp(jniEnv, j_value));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT ::djinni_generated::NTVDomainCustomer::JniType JNICALL Java_com_nativium_helper_SharedDataHelper_getCustomer(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::nativium::helper::SharedDataHelper::getCustomer();
        return ::djinni::release(::djinni_generated::NTVDomainCustomer::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_nativium_helper_SharedDataHelper_storeCustomer(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        ::nativium::helper::SharedDataHelper::storeCustomer();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nativium_helper_SharedDataHelper_setDemoFlag(JNIEnv* jniEnv, jobject /*this*/, jboolean j_value)
{
    try {
        ::nativium::helper::SharedDataHelper::setDemoFlag(::djinni::Bool::toCpp(jniEnv, j_value));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jboolean JNICALL Java_com_nativium_helper_SharedDataHelper_getDemoFlag(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::nativium::helper::SharedDataHelper::getDemoFlag();
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
