// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/helper/TodoHelper.hpp"

namespace djinni_generated {

class NTVHelperTodoHelper final : ::djinni::JniInterface<::nativium::helper::TodoHelper, NTVHelperTodoHelper> {
public:
    using CppType = std::shared_ptr<::nativium::helper::TodoHelper>;
    using CppOptType = std::shared_ptr<::nativium::helper::TodoHelper>;
    using JniType = jobject;

    using Boxed = NTVHelperTodoHelper;

    ~NTVHelperTodoHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVHelperTodoHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVHelperTodoHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVHelperTodoHelper();
    friend ::djinni::JniClass<NTVHelperTodoHelper>;
    friend ::djinni::JniInterface<::nativium::helper::TodoHelper, NTVHelperTodoHelper>;

};

}  // namespace djinni_generated
