// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/helper/SecurityHelper.hpp"

namespace djinni_generated {

class NTVHelperSecurityHelper final : ::djinni::JniInterface<::nativium::helper::SecurityHelper, NTVHelperSecurityHelper> {
public:
    using CppType = std::shared_ptr<::nativium::helper::SecurityHelper>;
    using CppOptType = std::shared_ptr<::nativium::helper::SecurityHelper>;
    using JniType = jobject;

    using Boxed = NTVHelperSecurityHelper;

    ~NTVHelperSecurityHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVHelperSecurityHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVHelperSecurityHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVHelperSecurityHelper();
    friend ::djinni::JniClass<NTVHelperSecurityHelper>;
    friend ::djinni::JniInterface<::nativium::helper::SecurityHelper, NTVHelperSecurityHelper>;

};

}  // namespace djinni_generated
