// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/helper/CustomerHelper.hpp"

namespace djinni_generated {

class NTVHelperCustomerHelper final : ::djinni::JniInterface<::nativium::helper::CustomerHelper, NTVHelperCustomerHelper> {
public:
    using CppType = std::shared_ptr<::nativium::helper::CustomerHelper>;
    using CppOptType = std::shared_ptr<::nativium::helper::CustomerHelper>;
    using JniType = jobject;

    using Boxed = NTVHelperCustomerHelper;

    ~NTVHelperCustomerHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVHelperCustomerHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVHelperCustomerHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVHelperCustomerHelper();
    friend ::djinni::JniClass<NTVHelperCustomerHelper>;
    friend ::djinni::JniInterface<::nativium::helper::CustomerHelper, NTVHelperCustomerHelper>;

};

}  // namespace djinni_generated
