// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/time/DateTime.hpp"

namespace djinni_generated {

class NTVDateTime final : ::djinni::JniInterface<::nativium::time::DateTime, NTVDateTime> {
public:
    using CppType = std::shared_ptr<::nativium::time::DateTime>;
    using CppOptType = std::shared_ptr<::nativium::time::DateTime>;
    using JniType = jobject;

    using Boxed = NTVDateTime;

    ~NTVDateTime();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVDateTime>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVDateTime>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVDateTime();
    friend ::djinni::JniClass<NTVDateTime>;
    friend ::djinni::JniInterface<::nativium::time::DateTime, NTVDateTime>;

};

}  // namespace djinni_generated
