// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/enumerator/NTVEnumeratorCustomerStatusEnum.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init_nativium_enumerator_customer_status_enum_consts, (), {
        Module.CustomerStatusEnum =  {
            ACTIVE : 0,
            INACTIVE : 1,
        }
    })
}

void NTVEnumeratorCustomerStatusEnum::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init_nativium_enumerator_customer_status_enum_consts();
    });
}

EMSCRIPTEN_BINDINGS(nativium_enumerator_customer_status_enum) {
    NTVEnumeratorCustomerStatusEnum::staticInitializeConstants();
}

}  // namespace djinni_generated
