// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/enumerator/CustomerStatusEnum.hpp"

namespace djinni_generated {

struct NTVEnumeratorCustomerStatusEnum: ::djinni::WasmEnum<::nativium::enumerator::CustomerStatusEnum> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
