// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export enum CustomerStatusEnum {
    ACTIVE = 0,
    INACTIVE = 1,
}

export interface AppEnumerator_statics {
}
